### ISSUE TITLE
Error when S3 bucket is incorrect

### ISSUE THREAD

**Issue by joeldenning** [ConvexCooperative/baseplate-cloudflare-worker#69]
```json
{
  "outcome": "ok",
  "scriptName": "cdn-tf-worker-dev",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [
    {
      "message": [
        "NoSuchBucket: The specified bucket does not exist"
      ],
      "level": "error",
      "timestamp": 1708464741916
    },
    {
      "message": [
        "The specified bucket does not exist"
      ],
      "level": "error",
      "timestamp": 1708464741916
    },
    {
      "message": [
        "NoSuchBucket: The specified bucket does not exist\n    at S3ServiceException2.ServiceException3 [as constructor] (main.js:9542:24)\n    at new S3ServiceException2 (main.js:9649:24)\n    at main.js:11694:22\n    at step (main.js:255:25)\n    at Object.next (main.js:202:20)\n    at fulfilled (main.js:173:30)"
      ],
      "level": "error",
      "timestamp": 1708464741916
    }
  ],
  "eventTimestamp": 1708464741718,
  "event": {
    "request": {
      "url": "https://dev-cdn.baseplate.cloud/convex/dev/apps/navbar/convex-navbar.js",
      "method": "GET",
      "headers": {
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "accept-encoding": "gzip",
        "accept-language": "en-US,en;q=0.9",
        "cache-control": "max-age=0",
        "cf-connecting-ip": "65.121.68.194",
        "cf-ipcountry": "US",
        "cf-ray": "8589dc9bbe926c3c",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "cookie": "REDACTED",
        "host": "dev-cdn.baseplate.cloud",
        "priority": "u=0, i",
        "sec-ch-ua": "\"Not A(Brand\";v=\"99\", \"Google Chrome\";v=\"121\", \"Chromium\";v=\"121\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\"",
        "sec-fetch-dest": "document",
        "sec-fetch-mode": "navigate",
        "sec-fetch-site": "none",
        "sec-fetch-user": "?1",
        "upgrade-insecure-requests": "1",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36",
        "x-forwarded-proto": "https",
        "x-real-ip": "65.121.68.194"
      },
      "cf": {
        "longitude": "-111.85650",
        "latitude": "40.73110",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "NA",
        "asn": 209,
        "clientAcceptEncoding": "gzip, deflate, br",
        "country": "US",
        "tlsClientRandom": "uo6tYqcUZwkUbwjF5Zpi64U4IB3nYxWuw2tyBHHb4aI=",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "verifiedBotCategory": "",
        "tlsExportedAuthenticator": {
          "clientFinished": "aa0ce921575dcbfbd819d220067de3dfde72ff7128576d70f02ec1f8074a5a7d",
          "clientHandshake": "79aa7a662490303273f996120db48092b9905c3e6d098593990f48ca5a6b44c3",
          "serverHandshake": "bcd17621800e8aaaf1e2e73e7a9210745fe1dd9370d6d6b6dbf4786110854723",
          "serverFinished": "38ae37a57f6bf3ae6d2110183d3329ec30fe2c581f0202a915fd0b60dfb98545"
        },
        "tlsVersion": "TLSv1.3",
        "city": "Salt Lake City",
        "timezone": "America/Denver",
        "colo": "DFW",
        "edgeRequestKeepAliveStatus": 1,
        "postalCode": "84105",
        "tlsClientHelloLength": "731",
        "region": "Utah",
        "httpProtocol": "HTTP/3",
        "regionCode": "UT",
        "asOrganization": "CenturyLink",
        "metroCode": "770",
        "requestPriority": ""
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 0
}
```

**Comment by joeldenning** [comment]
I think an HTTP 503 is the correct response code for this situation, ideally with a better error message. Right now it just says "cloudflare worker failed"

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503

**Comment by joeldenning** [comment]
This appears to be related to baseplate-web-app seeded environments not being 100% equivalent to environments created through Baseplate API. Since it's related to seeding, I'm closing this as not an issue with baseplate-cloudflare-worker.
